// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzuCF6FZklllXoF3bx5b-04WfQA2aS4_U',
    appId: '1:567556924559:web:270b92a0dacc2475683cfa',
    messagingSenderId: '567556924559',
    projectId: 'flutterapp-92668',
    authDomain: 'flutterapp-92668.firebaseapp.com',
    storageBucket: 'flutterapp-92668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnR8qIalub3iUDyarJj7RuDfWWj5MEb9A',
    appId: '1:567556924559:android:d4f964145505856e683cfa',
    messagingSenderId: '567556924559',
    projectId: 'flutterapp-92668',
    storageBucket: 'flutterapp-92668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8KK707tJBvwnJ5-8EuP9-3-DO_z-C1gw',
    appId: '1:567556924559:ios:c13fdb341c2ab8ee683cfa',
    messagingSenderId: '567556924559',
    projectId: 'flutterapp-92668',
    storageBucket: 'flutterapp-92668.appspot.com',
    iosBundleId: 'com.example.flutterQuizApp',
  );
}
